package tools;

import com.google.zxing.WriterException;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author eleon
 */
public class TestQR extends javax.swing.JPanel {
    
    private StringBuilder QR_STRING;
    private CodeBarUtils qrTools;
    
    
    /**
     * Creates new form TestQR
     */
    public TestQR() {
        initComponents();
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qrImage = new javax.swing.JLabel();
        btnGerateQR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQRString = new javax.swing.JTextArea();

        qrImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnGerateQR.setText("Generar QR");
        btnGerateQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerateQRActionPerformed(evt);
            }
        });

        txtQRString.setColumns(20);
        txtQRString.setRows(5);
        jScrollPane1.setViewportView(txtQRString);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qrImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerateQR, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qrImage, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGerateQR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerateQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerateQRActionPerformed
        
       
        try {
            int size = 220;
            qrTools = new CodeBarUtils();
            BufferedImage imgQR = qrTools.generateQR(txtQRString.getText().trim(), size);
            if( imgQR != null )
            {
                ImageIcon icon = new ImageIcon(imgQR);
                qrImage.setIcon(icon);
            }
            
            
        } catch (WriterException ex) {
            Logger.getLogger(TestQR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnGerateQRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerateQR;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel qrImage;
    public javax.swing.JTextArea txtQRString;
    // End of variables declaration//GEN-END:variables

    private void setValues() {
        QR_STRING = new StringBuilder();
        QR_STRING.append("https://ekuatia.set.gov.py/consultas-test/qr?nVersion=150&Id=01800524683001001000140322022120519498154504&dFeEmiDE");
        QR_STRING.append("=323032322d31322d30355431373a34323a3435&dRucRec=80052468&dTotGralOpe=39798.000&dTotIVA=3618.000&cItems=");
        QR_STRING.append("1&DigestValue=465237396565454e75327277696b4234334d75587871594f46724a596a6759684935693466304b53456c6f3d&IdCSC=");
        QR_STRING.append("0001&cHashQR=ab545ba5f03f036a3f4f243ea6170643b06025281c9eddd63c28077c0c0b2233");
       
        txtQRString.setText(QR_STRING.toString());
        txtQRString.setLineWrap(true);
        
    }
}
